### ISSUE TITLE
libstdc++ not found for macOS 10.13.6

### ISSUE THREAD

**Issue by tonytins** [endlesstravel/Love2dCS#108]
On macOS 10.13.6, I'm unable to run any game because it can't link to ``libstdc++``. I have tried installing GCC from Homebrew, Xcode 9 and 10 but I still get the same error. I've searched everywhere for workarounds but so I've come up empty handed. All I know is it changed from ``libstdc++`` to ``libc++`` sometime after GCC 4.2 and I don't know how to get 4.2 on a Mac without downgrading the operating system.

```
System.Exception: error on load libstdc++/libstdc++.so.6 System.Exception:  LibraryContentGenerator return null !
   at Love.NativeLibraryUtil.NativlibTool.WriteToTempDir(String tempDir, LibraryContent[] libToLoad)
   at Love.NativeLibraryUtil.NativlibTool.WriteToTempDir(String tempDir, LibraryContent[] libToLoad)
   at Love.NativeLibraryUtil.LibraryLoader.GetFunctionAddrLoader(LibraryContent[] libToLoad, INativeLibraryLoader loader)
   at Love.NativeLibraryUtil.LibraryLoader.Load(LibraryConfig config)
   at Love.Boot.InitNativeLibrary()
   at Love.Boot.Init(BootConfig bootConfig)
```

**Comment by endlesstravel** [comment]
The program recognize platform error as Linux but not MacOs.
fix it in version `11.0.50` : https://www.nuget.org/packages/Love2dCS/11.0.50
