### ISSUE TITLE
Joystick.IsConnected or JoyStick.IsDown(1) crashes love

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#45]
hello I have this code here that when it reaches the second line of the method it crashes

        public override void Update()
        {
            InputPrev = InputCurr;
            InputCurr = Joy.IsConnected() && Joy.IsDown(Key);
        }

![image](https://user-images.githubusercontent.com/2453707/54858733-ed97e800-4cc3-11e9-974d-572700fcde80.png)

**Comment by Shadowblitz16** [comment]
here is the demo project
https://drive.google.com/open?id=1LJGx11KsRysF2watXqXTVnLmfm6E_HLE

**Comment by endlesstravel** [comment]
I can't figure out what happend.

I just test your project, it's work fine.
(your code has bug that `InputMap.cs` on line 151, joyStick may be a null object.)

Here is may test code, it just work fine as well,

```C#using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Love;

namespace Project1
{
    class issues45 : Scene
    {
        public override void Update(float dt)
        {
            foreach (var joy in Joystick.GetJoysticks())
            {
                joy.IsConnected();
                for (int i = 0; i < joy.GetButtonCount(); i++)
                {
                    if (joy.IsDown(i))
                    {
                        Console.WriteLine($"joy {joy.GetName() + joy.GetGUID()} key {i} is down !");
                    }
                }

                GamepadButton[] gpbs = (GamepadButton[])System.Enum.GetValues(typeof(GamepadButton));
                foreach (var btn in gpbs)
                {
                    if (joy.IsGamepadDown(btn))
                    {
                        Console.WriteLine($"joy {joy.GetName() + joy.GetGUID()} gampad {btn} is down!");
                    }
                }
            }
        }


        static void Main(string[] args)
        {
            Boot.Init(new BootConfig
            {
            });
            Boot.Run(new issues45());
        }
    }
}

```

**Comment by Shadowblitz16** [comment]
idk its still happening. 

	System.AccessViolationException
		HResult=0x80004003
		Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
		Source=<Cannot evaluate the exception source>
		StackTrace:
	<Cannot evaluate the exception stack trace>

   at Love.Love2dDll._wrap_love_dll_type_Joystick_isConnected(IntPtr p, Boolean& out_result)
   at Love.Joystick.IsConnected()
   at BattleStars.Engine.ButtonMapJoystick.Update() in C:\Users\Shadowblitz16\source\repos\BattleStars\BattleStars.Engine\src\Btn\ButtonMap.cs:line 88
   at BattleStars.Engine.BtnPlayer.Update() in C:\Users\Shadowblitz16\source\repos\BattleStars\BattleStars.Engine\src\Btn.cs:line 124
   at BattleStars.Engine.Btn.Update() in C:\Users\Shadowblitz16\source\repos\BattleStars\BattleStars.Engine\src\Btn.cs:line 145
   at BattleStars.Engine.GameManager.Update(Single dt) in C:\Users\Shadowblitz16\source\repos\BattleStars\BattleStars.Engine\src\Game.cs:line 49
   at Love.Boot.Loop(BootConfig bootConfig, Scene scene)
   at Love.Boot.Run(Scene scene, BootConfig bootConfig)
   at BattleStars.Engine.Game.Run(Game game, Int32 gameW, Int32 gameH, Int32 gameFps, Int32 gameScale) in C:\Users\Shadowblitz16\source\repos\BattleStars\BattleStars.Engine\src\Game.cs:line 80
   at BattleStars.Program.Program.Main(String[] args) in C:\Users\Shadowblitz16\source\repos\BattleStars\BattleStars\src\Program.cs:line 14

**Comment by Shadowblitz16** [comment]
so here is a revamped version that tries to make sure sure that the joystick exists..

	public          class ButtonMapJoystick : ButtonMap
	{
			public Joystick      Joy;
			public int           Player;
			public int           Players;
			public override bool InputCurr { get; set; }
			public override bool InputPrev { get; set; }

			public ButtonMapJoystick(GamepadButton key, int player)
			{
					Key    = (int)key;
					Player = player;
			}
			public override void Update()
			{
					if (Joystick.GetJoystickCount() != Players)
					{
							Players = Joystick.GetJoystickCount();
							if (Player < Players) Joy = Joystick.GetJoysticks()[Player];
					}

					InputPrev = InputCurr;
					InputCurr = (Joy != null) ? Joy.IsConnected() && Joy.IsDown(Key) : false;
			}
	}

**Comment by Shadowblitz16** [comment]
@endlesstravel I figured out what it was.
its the red rockcandy xbox 360 controller I am using it crashes love.
here is a picture of it
https://i5.walmartimages.com/asr/029a0f17-9f5a-4c14-815e-353897f6c00b_1.2947e88f4b93170e31e057d2c5a14f76.jpeg?odnHeight=180&odnWidth=180&odnBg=FFFFFF

**Comment by endlesstravel** [comment]
I can't figure out what happend. 😭 

I tested all my controllers,  it is no crashed.

It is that Love crashed  only you use `red rockcandy xbox 360 controller` ?

**Comment by Shadowblitz16** [comment]
its the only controller I have besides the cheap snes controller most engines don't support.
but ya if the controller are unplugged love is fine, but if they are plugged in the it seems that it crashes on Joystick:IsSupported().

**Comment by endlesstravel** [comment]
That's strange. Original [Love](https://love2d.org) has no method `IsSupported` on Joystick.

![image](https://user-images.githubusercontent.com/10757838/55664110-86e60300-585b-11e9-88d6-c92a1ac5e9f3.png)

 did you mean is `Joystick:isConnected` ?

**Comment by Shadowblitz16** [comment]
ya i can just a sec

**Comment by endlesstravel** [comment]
en, Interesting things. I mean, can you test the code below?
If there no output on window, and i thinks there is some code environment make it invalid.
Can you email your sample project to me, so i can analysis what happend.

```C#
using System;
using Love;

namespace Project1
{
    class issues45 : Scene
    {
        string infoString = "";
        public override void Update(float dt)
        {
            foreach (var key in (KeyConstant[])Enum.GetValues(typeof(KeyConstant)))
            {
                if (Keyboard.IsPressed(key))
                {
                    infoString += key.ToString() + " is Pressed. \n";
                }
            }
        }

        public override void Draw()
        {
            Graphics.Print(infoString);
        }

        static void Main(string[] args)
        {
            Boot.Init(new BootConfig
            {
            });
            Boot.Run(new issues45());
        }
    }
}

```

**Comment by Shadowblitz16** [comment]
this doesn't draw or print anything
```
using System;
using Love;

namespace LoveControllerTest
{
    class Program : Scene
    {
        string infoString = "";
        public override void Update(float dt)
        {
            foreach (var key in (KeyConstant[])Enum.GetValues(typeof(KeyConstant)))
            {
                if (Keyboard.IsPressed(key))
                {
                    infoString += key.ToString() + " is Pressed. \n";
                }
            }
        }

        public override void Draw()
        {
            Graphics.SetColor(Color.White);
            Graphics.Print(infoString);
        }

        static void Main(string[] args)
        {
            Boot.Init(new BootConfig
            {
            });
            Boot.Run(new Program());
        }
    }
}
```
